### ISSUE TITLE
The root issue for all TODOs

### ISSUE THREAD

**Issue by sergeypospelov** [UnitTestBot/usvm#11]
This issue contains all TODOs, so as not to forget them. If you complete any todo from this list, don't forget to add a link to the report in some form.

# TODOs

- [ ] Benchmark different ways of collecting a guard  in the `HeapRefSplittingUtil::filter`.
- [ ] Make a single ite not only for symbolic heap refs, but for concrete heap refs too.
- [ ] Compare eager and lazy `UModel` performance. 
- [x] Structure source files into packages. **Fixed in #13**
- [x] Add simplifying `UFlatUpdates` in `UComposer`  (case composing on UModel, where stores are concretized and we expect a concrete reading returns a concrete value). **Added in #9**
- [ ] `mkDistinct` with concrete heap refs.
- [ ] Interning `URegionId`s.
- [ ] Choose constant names carefully in `UExprTranslator`.
- [ ] Deal with big arrays in composition. Idea: we can create a ranged update node with copy from big array and apply it to heap.
- [ ] Localized map in memory regions compostion.
- [ ] Refactor `UHeap` to generic implementation with `getMemoryRegion(regionId: URegionId)`.
- [ ] Fix `Type`/`ArrayType` inconsistence.
- [ ] Make recursive-free implementations in `UFlatUpdates`.
- [x] Implement `UMemory::memset`. **Added in #17**
- [ ] Revision and design `UComponents` and DI in `usvm`.
- [ ] Implement approximations for `Throwable`.
- [ ] Choose a better way to place `close` function, related to [this PR](https://github.com/UnitTestBot/usvm/pull/20).
- [x] Refactor namings in `RegionTree` and all usages. **Fixed in #26**
- [ ] Fix equals for update nodes and add related tests.
- [ ] Think again about array casts and type elations with their elements.
- [ ] Think about region refinement with bv constraints and their interaction with memory regions (eager vs lazy style). `includesConcretely`, `includesSymbolically` look like good extension points.
- [x] Fix translator cache usage in lazy models. **Fixed in #28**
- [ ] Make cache in `DfsIterator` optional
- [ ] Refactor the splitting read mechanism.
